name: Deploy Manually

# Triggered manually
on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: tech-bytes-kyma-cicd

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: 2021-08-02-github-actions-kyma

      - run: npm install

      - run: npm run build

      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ghcr.io/tech-bytes-kyma-cicd
          labels: ${{ steps.meta.outputs.labels }}


      - name: push service
        run: |
          docker push ghcr.io/tech-bytes-kyma-cicd

      - uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.DEV_KUBECONFIG }}
          command: apply -n tutorial -f ./k8s/dev_deployment.yaml